# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46c614dcffc7d5c431a894515134cde47e2ada4fb5f27b23e106dbc5feb652d34a53c3723eb960b88bada920edd56bc8a2963760ced362ed04c183a9c5db096d

test:
  secret_key_base: 5b4e2f7e63f62d50b7a49e6ef93d44aa83eea5254a4127d0f7381a67b5220f3e3e7e535efa8a04fee1c32469b7af3b997372a40516516031399d53dc71a69717

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
